spring:
  jpa:
    hibernate:
      ddl-auto: create

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

admin:
  token: "admin"