spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  devtools:
    add-properties: false

server:
  port: ${PORT}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}