spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587

jwt:
  secret: ${JWT_SECRET_KEY}

errorping:
  channelId: ${ERRORPING_CHANNEL_ID}
  apiKey: ${ERRORPING_API_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  override-with-generic-response: false