spring:
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080

admin:
  email: "admin@admin.com"
  password: "admin"
  api-key: "local-admin-key"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html